batch_size: 256
classifier_epochs: 3
brain_module_epochs: 200
classifier_lr: 0.001
brain_module_lr: 0.0003
loss_weight: 0.95

device: cuda
num_workers: 4
seed: 1234
use_wandb: False
use_cache: True
start_from_best: False

data_dir: /content/data
image_module:
  repo: "facebookresearch/dinov2"
  model: "dinov2_vits14"

# Evaluation
model_path:
