batch_size: 128
epochs: 10
lr: 0.001

device: cuda
num_workers: 4
seed: 1234
use_wandb: False

data_dir: data
image_module:
  repo: "facebookresearch/dinov2"
  model: "dinov2_vits14"

# Evaluation
model_path:
