batch_size: 128
classifier_epochs: 5
brain_module_epochs: 10
classifier_lr: 0.001
brain_module_lr: 0.0003
loss_weight: 0.5

device: cuda
num_workers: 4
seed: 1234
use_wandb: False

data_dir: /content/data
image_module:
  repo: "pytorch/vision:v0.10.0"
  model: "resnet18"

# Evaluation
model_path:
